--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-16-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APC_CANCEL
--------------------------------------------------------

  CREATE TABLE "SEMI"."APC_CANCEL" 
   (	"CANCEL_NO" NUMBER(7,0), 
	"ORDERNO_FK" NUMBER(5,0), 
	"PNO_FK" NUMBER(5,0), 
	"MEMID_FK" VARCHAR2(50 BYTE), 
	"PNAME" VARCHAR2(50 BYTE), 
	"PCOLOR" VARCHAR2(50 BYTE), 
	"PSIZE" VARCHAR2(100 BYTE), 
	"PQTY" NUMBER(5,0), 
	"CANCEL_CATEGORY" VARCHAR2(50 BYTE), 
	"CANCEL_CONT" VARCHAR2(1000 BYTE), 
	"CANCEL_IMAGE" VARCHAR2(100 BYTE), 
	"CANCEL_DATE" DATE, 
	"CANCEL_STATE" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SEMI.APC_CANCEL
SET DEFINE OFF;
Insert into SEMI.APC_CANCEL (CANCEL_NO,ORDERNO_FK,PNO_FK,MEMID_FK,PNAME,PCOLOR,PSIZE,PQTY,CANCEL_CATEGORY,CANCEL_CONT,CANCEL_IMAGE,CANCEL_DATE,CANCEL_STATE) values (1,1,3,'tlsruddus','Sermaise T-Shirts (white)','WHITE','XS',1,'제품 오배송','제품이 잘못왔어요','1.jpg',to_date('22/05/16','RR/MM/DD'),0);
Insert into SEMI.APC_CANCEL (CANCEL_NO,ORDERNO_FK,PNO_FK,MEMID_FK,PNAME,PCOLOR,PSIZE,PQTY,CANCEL_CATEGORY,CANCEL_CONT,CANCEL_IMAGE,CANCEL_DATE,CANCEL_STATE) values (2,4,4,'tlsruddus','Sermaise T-Shirts (white)','WHITE','S',1,'사이즈','사이즈 잘못왔어요','2.jpg',to_date('22/05/16','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index SYS_C007872
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."SYS_C007872" ON "SEMI"."APC_CANCEL" ("CANCEL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APC_CANCEL
--------------------------------------------------------

  ALTER TABLE "SEMI"."APC_CANCEL" MODIFY ("ORDERNO_FK" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CANCEL" MODIFY ("PNO_FK" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CANCEL" MODIFY ("MEMID_FK" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CANCEL" ADD PRIMARY KEY ("CANCEL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
