--------------------------------------------------------
--  ?뚯씪???앹꽦??- ?섏슂??5??11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APC_CART
--------------------------------------------------------

  CREATE TABLE "SEMI"."APC_CART" 
   (	"CART_NO" NUMBER(5,0), 
	"PNO_FK" NUMBER(5,0), 
	"CART_MEMID" VARCHAR2(50 BYTE), 
	"CART_PNAME" VARCHAR2(100 BYTE), 
	"CART_PQTY" NUMBER(5,0), 
	"CART_PSIZE" VARCHAR2(100 BYTE), 
	"CART_PCOLOR" VARCHAR2(50 BYTE), 
	"CART_PRICE" NUMBER(8,0), 
	"CART_TRANS" NUMBER(8,0) DEFAULT 0, 
	"CART_PIMAGE" VARCHAR2(500 BYTE), 
	"CART_MILEAGE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SEMI.APC_CART
SET DEFINE OFF;
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (9,8,'non0','Saules T-Shirts (black)',1,'XS','BLACK',319000,0,'/3WAT0000/wTshirt2_1b.jpg',19140);
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (1,3,'hong','Sermaise T-Shirts (white)',1,'XS','WHITE',289000,3000,null,null);
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (2,1,'funfun','Quincy Knit Vest (indigo)',1,'XS','WHITE',489000,3000,null,null);
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (3,1,'hong','Quincy Knit Vest (indigo)',1,'XS','WHITE',489000,3000,null,null);
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (10,8,'hong','Saules T-Shirts (black)',1,'XS','BLACK',319000,0,'/3WAT0000/wTshirt2_1b.jpg',19140);
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (6,8,'non0','Saules T-Shirts (black)',1,'BLACK','BLACK',319000,3000,'/3WAT0000/wTshirt2_1b.jpg',null);
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (7,8,'hong','Saules T-Shirts (black)',1,'XS','BLACK',319000,0,'/3WAT0000/wTshirt2_1b.jpg',19140);
Insert into SEMI.APC_CART (CART_NO,PNO_FK,CART_MEMID,CART_PNAME,CART_PQTY,CART_PSIZE,CART_PCOLOR,CART_PRICE,CART_TRANS,CART_PIMAGE,CART_MILEAGE) values (8,8,'non0','Saules T-Shirts (black)',1,'XS','BLACK',319000,0,'/3WAT0000/wTshirt2_1b.jpg',19140);
--------------------------------------------------------
--  DDL for Index SYS_C007886
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."SYS_C007886" ON "SEMI"."APC_CART" ("CART_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APC_CART
--------------------------------------------------------

  ALTER TABLE "SEMI"."APC_CART" MODIFY ("PNO_FK" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CART" MODIFY ("CART_MEMID" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CART" MODIFY ("CART_PNAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CART" MODIFY ("CART_PQTY" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CART" MODIFY ("CART_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CART" ADD PRIMARY KEY ("CART_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APC_CART
--------------------------------------------------------

  ALTER TABLE "SEMI"."APC_CART" ADD FOREIGN KEY ("PNO_FK")
	  REFERENCES "SEMI"."APC_PRODUCTS" ("PNO") ENABLE;
