--------------------------------------------------------
--  ?뚯씪???앹꽦??- ?섏슂??5??11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APC_CATEGORY
--------------------------------------------------------

  CREATE TABLE "SEMI"."APC_CATEGORY" 
   (	"CATEGORY_NO" NUMBER(5,0), 
	"CATEGORY_CODE" VARCHAR2(8 BYTE), 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"CATEGORY_IMAGE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SEMI.APC_CATEGORY
SET DEFINE OFF;
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'20000000','MEN',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'30000000','GOLF',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MAN0000','WOMEN/TSHIRTS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WAN0000','WOMEN/NEW ARRIVALS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WCS0000','WOMEN/SHOES',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WDC0000','WOMEN/COATS, PARKAS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WEJ0000','WOMEN/JACKETS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WFD0000','WOMEN/DRESSES',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WBB0000','WOMEN/BAGS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WGS0000','WOMEN/SKIRTS, SHORTS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WHT0000','WOMEN/TROUSERS, JEANS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WIB0000','WOMEN/BLOUSES, SHIRTS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WJK0000','WOMEN/KNITWEAR, CARDIGANS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WKT0000','WOMEN/T-SHIRTS, PULLOVERS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WLL0000','WOMEN/LEATHEr GOODS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'1WMS0000','WOMEN/SMALL ACCESSORIES',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MBC0000','MEN/COATS, PARKAS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MCJ0000','MEN/JACKETS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MDT0000','MEN/TROUSERS, JEANS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MES0000','MEN/SHIRTS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MFK0000','MEN/KNITWEAR, CARDIGANS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MGT0000','MEN/T-SHIRTS, PULLOVERS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MHB0000','MEN/BAGS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MIS0000','MEN/SHOES',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MJL0000','MEN/LEATHEr GOODS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MKJ0000','MEN/JEWELRY',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (2,'2MLS0000','MEN/SMALL ACCESSORIES',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3W000000','WOMEN',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3M000000','MEN',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3A000000','ACC',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3WAT0000','WOMEN/TSHIRTS','gw_tshirts.jpg');
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3WBK0000','WOMEN/KNIT','gw_knit.jpg');
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3WCO0000','WOMEN/OUTER','gw_outer.jpg');
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3WDP0000','WOMEN/PANTS','gw_pants.jpg');
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3WES0000','WOMEN/SKIRTS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3WFD0000','WOMEN/DRESS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3MAT0000','MEN/TSHIRTS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3MBK0000','MEN/KNIT',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3MCO0000','MEN/OUTER',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (3,'3MDP0000','MEN/PANTS',null);
Insert into SEMI.APC_CATEGORY (CATEGORY_NO,CATEGORY_CODE,CATEGORY_NAME,CATEGORY_IMAGE) values (1,'10000000','WOMEN',null);
--------------------------------------------------------
--  DDL for Index SYS_C007871
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."SYS_C007871" ON "SEMI"."APC_CATEGORY" ("CATEGORY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APC_CATEGORY
--------------------------------------------------------

  ALTER TABLE "SEMI"."APC_CATEGORY" MODIFY ("CATEGORY_NO" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_CATEGORY" ADD PRIMARY KEY ("CATEGORY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
