--------------------------------------------------------
--  ?뚯씪???앹꽦??- ?섏슂??5??11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APC_PAYMENT
--------------------------------------------------------

  CREATE TABLE "SEMI"."APC_PAYMENT" 
   (	"ORDER_NO" NUMBER(5,0), 
	"CARTNO_FK" NUMBER(5,0), 
	"ORDER_ID" VARCHAR2(100 BYTE), 
	"PNO_FK" VARCHAR2(8 BYTE), 
	"PNAME" VARCHAR2(50 BYTE), 
	"PQTY" NUMBER(5,0), 
	"PRICE" NUMBER(10,0), 
	"TRANSCOST" NUMBER(10,0) DEFAULT 0, 
	"PAYTYPE" NUMBER(1,0), 
	"ORDERDATE" DATE, 
	"ORDERNAME" VARCHAR2(50 BYTE), 
	"ORDERADDR" VARCHAR2(1000 BYTE), 
	"ORDERPHONE" VARCHAR2(50 BYTE), 
	"PAY_PIMAGE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SEMI.APC_PAYMENT
SET DEFINE OFF;
Insert into SEMI.APC_PAYMENT (ORDER_NO,CARTNO_FK,ORDER_ID,PNO_FK,PNAME,PQTY,PRICE,TRANSCOST,PAYTYPE,ORDERDATE,ORDERNAME,ORDERADDR,ORDERPHONE,PAY_PIMAGE) values (1,1,'hong','3','Sermaise T-Shirts (white)',1,289000,3000,1,to_date('22/05/02','RR/MM/DD'),'?띻만??,'?쒖슱??援щ줈援?,'010-1111-1111',null);
Insert into SEMI.APC_PAYMENT (ORDER_NO,CARTNO_FK,ORDER_ID,PNO_FK,PNAME,PQTY,PRICE,TRANSCOST,PAYTYPE,ORDERDATE,ORDERNAME,ORDERADDR,ORDERPHONE,PAY_PIMAGE) values (2,2,'funfun','1','Quincy Knit Vest (indigo)',1,489000,3000,1,to_date('22/05/02','RR/MM/DD'),'?좎옱??,'?쒖슱??媛뺣궓援?,'010-2111-1111',null);
Insert into SEMI.APC_PAYMENT (ORDER_NO,CARTNO_FK,ORDER_ID,PNO_FK,PNAME,PQTY,PRICE,TRANSCOST,PAYTYPE,ORDERDATE,ORDERNAME,ORDERADDR,ORDERPHONE,PAY_PIMAGE) values (3,3,'hong','1','Quincy Knit Vest (indigo)',1,489000,3000,1,to_date('22/05/02','RR/MM/DD'),'?띻만??,'?쒖슱??援щ줈援?,'010-1111-1111',null);
--------------------------------------------------------
--  DDL for Index SYS_C007902
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."SYS_C007902" ON "SEMI"."APC_PAYMENT" ("ORDER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APC_PAYMENT
--------------------------------------------------------

  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("PNO_FK" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("PQTY" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("PAYTYPE" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("ORDERDATE" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("ORDERNAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("ORDERADDR" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" MODIFY ("ORDERPHONE" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."APC_PAYMENT" ADD CHECK (paytype < 3) ENABLE;
  ALTER TABLE "SEMI"."APC_PAYMENT" ADD PRIMARY KEY ("ORDER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APC_PAYMENT
--------------------------------------------------------

  ALTER TABLE "SEMI"."APC_PAYMENT" ADD FOREIGN KEY ("CARTNO_FK")
	  REFERENCES "SEMI"."APC_CART" ("CART_NO") ENABLE;
